/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var l=Object.defineProperty;var f=Object.getOwnPropertyDescriptor;var u=Object.getOwnPropertyNames;var m=Object.prototype.hasOwnProperty;var g=(o,e)=>{for(var t in e)l(o,t,{get:e[t],enumerable:!0})},$=(o,e,t,i)=>{if(e&&typeof e=="object"||typeof e=="function")for(let n of u(e))!m.call(o,n)&&n!==t&&l(o,n,{get:()=>e[n],enumerable:!(i=f(e,n))||i.enumerable});return o};var h=o=>$(l({},"__esModule",{value:!0}),o);var w={};g(w,{default:()=>c});module.exports=h(w);var r=require("obsidian"),c=class extends r.Plugin{async onload(){this.addCommand({id:"copy-cursor-position",name:"Copy cursor position to clipboard",checkCallback:e=>{let t=this.app.workspace.getActiveViewOfType(r.MarkdownView);if(!(t!=null&&t.file))return!1;if(!e){let i=t.editor,n=t.file.path,p=i.getSelection(),s;if(p){let a=i.getCursor("from").line+1,d=i.getCursor("to").line+1;s=`${n}:
Lines ${a}-${d}:
\`\`\`${p}\`\`\``}else{let a=i.getCursor().line+1;s=`${n}:Lines ${a}`}navigator.clipboard.writeText(s).then(()=>{new r.Notice(`Copied: ${s}`)})}return!0}})}};
